### ISSUE TITLE
Filter table of materials copied from Shield-Hit12A

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#114]
- [x] Add autocomplete searchbar to zone material config
- [x] Hide uncommon materials from select ui
- [x] Add button to save json of three material parameters for simulation materials
![image](https://user-images.githubusercontent.com/26445545/141855245-04873e92-8834-4049-a621-21bd07d166d0.png)

**Comment by grzanka** [comment]
Take a look also here:
https://github.com/yaptide/yaptide/discussions/60#discussioncomment-1322805

**Comment by ostatni5** [comment]
@grzanka Can you provide a common materials list?

**Comment by grzanka** [comment]
@ostatni5 common materials should include:
 - liquid water
 - air
 - PMMA (Lucite)
 - Kapton
 - Mylar
 - Carbon
 - Silicon
 - Lead
