### ISSUE TITLE
Local deploy tries to connect to keycloak

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1141]
We should consider reconfiguring or disabling keycloak service for local deployment.

The steps to reproduce:

1. Clone backend (master) and bring it up with `docker compose up -d --build`
2. Once ready add first local user: `docker exec -w /usr/local/app/ yaptide_flask python3 yaptide/admin/db_manage.py add-user admin --password mysecretpassword`
3. Clone frontent (master) and bring it up with `docker compose up -d --build`
4. Open browser and load frontend using plain (not HTTPS!!!) by typing: `http://localhost` (not `https://localhost` !!)
5. Login as admin/mysecretpassword
6. Submit some simulation for local execution
7. After 2.5 minutes (150s) you will be automatically logged out. That should not happen.

Here is the timing of events:
1. Second 0 we open the app:
![image](https://github.com/yaptide/ui/assets/7374733/a632950d-66ff-4614-b805-21f2a5ad6672)

2. At 25s we submit a simulation:
![image](https://github.com/yaptide/ui/assets/7374733/d38acccf-8324-46f5-add3-eeba81de8671)

3. At 1.1 min we have the results:
![image](https://github.com/yaptide/ui/assets/7374733/ad83bc41-83be-4b34-8180-fc97f32073b4)
![image](https://github.com/yaptide/ui/assets/7374733/26bdf6d2-b39b-4107-a47e-3ebac0602cd2)

4. At 2.5 min we are logged out. There goes a request to `sso.pre.plgrid.pl`, but I ran the test on my own laptop, hence no access there:
![image](https://github.com/yaptide/ui/assets/7374733/7796036e-5bf7-4962-88c7-b51af479f6a3)

![image](https://github.com/yaptide/ui/assets/7374733/885d54dc-a8ad-4afa-bcc0-8cf39155158e)

**Comment by grzanka** [comment]
We could consider also a way to set a local keycloak, but maybe for local development we can simply disable "plgrid" option ?

**Comment by grzanka** [comment]
Funny enough the local build has `REACT_APP_ALT_AUTH` not set.

Dockerfile does:
`RUN npx cross-env REACT_APP_DEPLOYMENT=${DEPLOYMENT} npm run build`

In package json we have:
```
		"build": "react-app-rewired build",
		"build-plg": "cross-env REACT_APP_ALT_AUTH=plg npm run build",
		"build-demo": "cross-env REACT_APP_TARGET=demo npm run build",
```
In the config file we have
```
const ALT_AUTH = process.env.REACT_APP_ALT_AUTH === 'plg';
```

The PLGRID login button is disabled hence I would expect that no calls to keycloak are made.

![image](https://github.com/yaptide/ui/assets/7374733/06667a98-c699-4a0e-beed-84934e758c90)

**Comment by grzanka** [comment]
On `yap-dev` I set `REACT_APP_ALT_AUTH` to enable PLGRID login on contrary

**Comment by hendzeld** [comment]
Now, we have automatic redirection to HTTPs in local env (nginx).
I had to change the configuration.
Seems that it works fine now.

## Logging out


![Image](https://github.com/yaptide/ui/assets/128628266/73dbfa7f-ee71-4993-ac25-2f90f4a844e8)

![Image](https://github.com/yaptide/ui/assets/128628266/52bcb076-40b8-439f-8b85-706fad23d04d)

Result, more than 2 minutes, still logged in.

![Image](https://github.com/yaptide/ui/assets/128628266/c51e780e-f12e-464c-8a18-bf55e4bb7634)

Summary. Seems that it works now.

## Build

By default, Docker image is created using prod env

```
# Default deployment type can be overwritten by docker build --build-arg DEPLOYMENT=dev ...
ARG DEPLOYMENT=prod

RUN echo "Deploying for ${DEPLOYMENT}"

# Build the app.
RUN npx cross-env REACT_APP_DEPLOYMENT=${DEPLOYMENT} npm run build
```

I had set K8S variables during build, with default `DEPLOYMENT` value.
I do not see any requests to KC

**Comment by hendzeld** [comment]
To get full picture, application was tested with `npm run start` and `.env`: 

```
REACT_APP_KEYCLOAK_BASE_URL=http://localhost:8080
REACT_APP_KEYCLOAK_REALM=local
REACT_APP_KEYCLOAK_CLIENT_ID=yaptide
REACT_APP_ALT_AUTH=plg
```

http://localhost:3000/

Local was not logged out.


![Image](https://github.com/yaptide/ui/assets/128628266/1b4739b2-1000-47e7-a0eb-e8a859ffdc0d)
