### ISSUE TITLE
Input file generation fails on production demo on github pages

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1257]
It seems like the example JSON files are loaded from master or from web_dev installation:

![image](https://github.com/yaptide/ui/assets/7374733/1462e1d8-6083-48f2-ab00-7ed0892768fe)

Is it related to hardcoded web_dev here ?
https://github.com/yaptide/ui/blob/8a39a448c9f3dc190775ae3f598ff3be8f8ec2f9/package.json#L78

**Comment by dudiiiiiiii** [comment]
Won't reproduce
