### ISSUE TITLE
Unwated redirect to SSO

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1307]
I went to a website https://yap-dev.c3.plgrid.pl . I haven't specified any SSH proxy, also I wasn't planning to log in.

![image](https://github.com/yaptide/ui/assets/7374733/016e362c-8f6a-47da-9ed6-82a3ac0ae685)

In about 30 seconds I got automatically redirected to following site.

```
https://sso.pre.plgrid.pl/auth/realms/PLGrid/protocol/openid-connect/auth?client_id=yaptide-staging&redirect_uri=https%3A%2F%2Fyap-dev.c3.plgrid.pl%2F&state=(...)
```

![image](https://github.com/yaptide/ui/assets/7374733/b8e1bed6-fb46-4460-affd-11880c560ac9)

Is there any authomaticall and periodical redirect to keycloak in a situation where user is not logged in ?

**Comment by hendzeld** [comment]
Signing in using standard user.

![peek_yaptide_web](https://github.com/yaptide/ui/assets/128628266/485c1274-7e77-4cf0-a33c-bc80894840e5)

**Comment by hendzeld** [comment]
Related PR https://github.com/yaptide/ui/pull/1364
