### ISSUE TITLE
Check which input particle types makes sense to include

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1357]
Probably some of the won't work, some of them may not be useful at all (say neutrinos?)

**Comment by Bogdan2423** [comment]
I tested SHIELDHIT-12A on proton pencil beam example with all available particles. All particles gave results which looked fine, with the following excepions:
*  Pion pi0 (5) gave no results (empty plots)
*  For Gamma radiation (12) simulation failed
*  Muons (15, 16) there were no results except dose
*  For heavy ion (25) simulation failed if no HIPROJ card with A and Z values was provided, even though docs state that carbon-12 is default in case the card is omitted. When HIPROJ is defined it works normally

I tested Fluka on colimator input file. This time the exceptions were:
* Pion 0, gamma radiation and muons gave no results for fluence with proton filter, but there were results for dose

**Comment by grzanka** [comment]
> I tested SHIELDHIT-12A on proton pencil beam example with all available particles. All particles gave results which looked fine, with the following excepions:
> 
> * Pion pi0 (5) gave no results (empty plots)

Can you check "fluence" without any filters for pi0 ?

> * For Gamma radiation (12) simulation failed

That is expected, we should exclude photons (gamma radiation) from input particle list for SHIELD-HIT12A. This simulator code cannot handle transport of photons.

> * Muons (15, 16) there were no results except dose

That was expected. One should check as well "fluence" without any filter. I would expect some results there.

> * For heavy ion (25) simulation failed if no HIPROJ card with A and Z values was provided, even though docs state that carbon-12 is default in case the card is omitted. When HIPROJ is defined it works normally

All heavy ions should go as input particles for SH12A.

> I tested Fluka on colimator input file. This time the exceptions were:
> 
> * Pion 0, gamma radiation and muons gave no results for fluence with proton filter, but there were results for dose

That means that pion0, gamma and muons are to be included in input particle list for Fluka. It is expected that "proton fluence" is zero.

**Comment by Bogdan2423** [comment]
> Can you check "fluence" without any filters for pi0 ?
I removed all filters from all detectors on proton pencil beam example, still no results for pi0. All plots are empty, all scalar results are 0.
> That was expected. One should check as well "fluence" without any filter. I would expect some results there.
Fluence without filters gave normal results for these particles.

**Comment by grzanka** [comment]
As for now remove unsupported SHIELD-HIT12A particles.
