### ISSUE TITLE
Fix particle name in JSON

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1378]
https://github.com/yaptide/ui/pull/1370

I've opened example 01 and run the simulation

![image](https://github.com/yaptide/ui/assets/7374733/170d7516-8ebe-402f-94eb-650636746686)

Do we need to update example's JSON's as well ?

**Comment by Bogdan2423** [comment]
Apparently this was fixed with this PR: https://github.com/yaptide/ui/pull/1377
