### ISSUE TITLE
Enable plot menu by default

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1557]
Right now the menu is hidden:

![image](https://github.com/yaptide/ui/assets/7374733/a07acd66-e42e-4f90-bc61-f7aa9c270a30)

when selected it looks like that:

![image](https://github.com/yaptide/ui/assets/7374733/5c301239-c41f-4b74-b641-2fc18fd80db2)

**Comment by mmroz123** [comment]
test_comment
