### ISSUE TITLE
Add position & rotation info to project file

### ISSUE THREAD

**Issue by ostatni5** [yaptide/ui#158]
Add info about the rotation of object in degrees. (XYZ)
Add info about the position of object. (XYZ)

Currently, that info is in a matrix.
![obraz](https://user-images.githubusercontent.com/26521377/137728412-287d0285-1a55-4221-9774-864457fe9314.png)

**Comment by retkiewi** [comment]
All relevant info is already contained in the `children` array inside of the `scene.object` object. Objects in the children array allow for custom props (the geometries objects do not) and therefore seem like a better place to store translations (which they already do).
