### ISSUE TITLE
Move objects with info about simulation to single object

### ISSUE THREAD

**Issue by ostatni5** [yaptide/ui#162]
![obraz](https://user-images.githubusercontent.com/26521377/137748422-0ca583c6-fa29-4796-8137-bad39ac4c2af.png)

And consider moving signals used only by yaptide part of editor to it.
![obraz](https://user-images.githubusercontent.com/26521377/137748567-d1191054-3681-493c-b780-c625127a01a3.png)

**Comment by Derstilon** [comment]
Integration of threejs editor with simulation components tightened so now this changes would be obsolete.
objects with info about simulation are partially collected in physics component.
