### ISSUE TITLE
Fix beam arrow visibility with cropping planes

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#170]
Arrow depicting beam seems to be not affected by cropping planes:
It is visible respectively of what kind of cropping we apply
![image](https://user-images.githubusercontent.com/7374733/138169409-1a457a69-d2e0-4c3a-b9df-c54765e14afe.png)

_Originally posted by @grzanka in https://github.com/yaptide/ui/issues/163#issuecomment-948022759_

**Comment by Derstilon** [comment]
![image](https://github.com/yaptide/ui/assets/26445545/2f315009-81d2-4b4e-8cc0-eabf7309d4f2)
