### ISSUE TITLE
(JS-0242) Use `const` declarations for variables that are never reassigned

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#202]
## Description
Variables that are not re-assigned are referred to as constant variables. So, we recommend using `const` for such variables instead of `let` to define because the value of a variable declared with const remains the same within its scope. It cannot be updated or re-declared and also reduces cognitive load …

## Occurrences
There are 255 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/yaptide/ui/issue/JS-0242/occurrences/](https://deepsource.io/gh/yaptide/ui/issue/JS-0242/occurrences/)

**Comment by Derstilon** [comment]
Will do in next PR
