### ISSUE TITLE
add multiple view to viewport

### ISSUE THREAD

**Issue by ostatni5** [yaptide/ui#25]
https://threejs.org/examples/?q=multip#webgl_multiple_views

**Comment by grzanka** [comment]
The view should consist of 3D view and 3 sections, like here:
![image](https://user-images.githubusercontent.com/7374733/132244585-e91c45e3-e890-44ef-a5fc-5d090bc35096.png)
(from https://fluka.cern/news/release-flair-30-new-licence)

**Comment by grzanka** [comment]
User should be able to choose the coordinate at which section is being made. Simplest choice - scrollbar, as here:
https://threejs.org/examples/#webgl_clipping_stencil

**Comment by grzanka** [comment]
See also https://github.com/yaptide/ui/issues/24
