### ISSUE TITLE
Add remaining simulation materials to frontend ui

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#253]
- [x] All missing materials based on periodic table, and special materials: black hole and vacuum

- [x] Add vacuum to common list

- [ ] Stylize visualization of common materials to be at least somewhat decent.

**Comment by grzanka** [comment]
Needed by snowman example: lead material

**Comment by grzanka** [comment]
@grzanka write here where this is specified, I could help by coding it.

**Comment by ostatni5** [comment]
@grzanka 
File with materials
ui\src\ThreeEditor\util\Materials\materials.ts
https://github.com/yaptide/ui/blob/master/src/ThreeEditor/util/Materials/materials.ts
