### ISSUE TITLE
Consider replacing buildng app with Docker that uses node.js to build files

### ISSUE THREAD

**Issue by ostatni5** [yaptide/ui#264]
![obraz](https://user-images.githubusercontent.com/26521377/142450126-5131622c-f1b1-4d99-bbe4-454af2ce1724.png)

Consider replacing this with Docker one-liner

_Originally posted by @grzanka in https://github.com/yaptide/ui/pull/257#discussion_r750506769_

**Comment by grzanka** [comment]
We will use docker compose instead

**Comment by grzanka** [comment]
Such approach is now implemented in the deploy repo: https://github.com/yaptide/deploy/blob/f5023c4b30c433c025cde1602c2d95c95548b354/roles/frontend/tasks/deploy.yml#L46
