### ISSUE TITLE
Fix minor issues in the output JSON

### ISSUE THREAD

**Issue by retkiewi** [yaptide/ui#316]
- [x] Default zone material is not saved in json. (Materials probably update only on material change, but also should on zone creation).
- [x] Worldzone has no uuid.
- [x] ~~Userdata in worldzone has no rotation, but should have to be consistent with other geometries.~~

- [x] Sphere can be scaled axis-wise, but only the radius should be scalable.

- [x] Default worldzone has no volume (size of 0 in each axis), it probably should scale automatically by default or at least be bigger.

**Comment by grzanka** [comment]
@retkiewi what is the status. Add a checkbox with sub-tasks
