### ISSUE TITLE
Add units to the input fields for differential scorers

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#319]
> Units should be added to input fields for differential scorers: ![image](https://user-images.githubusercontent.com/7374733/145582036-db4043f0-fd70-4b84-87cd-0c7c81f84604.png)
> 
> in a similar way as done in other places: ![image](https://user-images.githubusercontent.com/7374733/145582100-29a71ef4-64b8-44dc-b480-0a91c13d935b.png)

![image](https://user-images.githubusercontent.com/26445545/145606309-2fb5ba1e-f346-4328-9b2a-eee701f4928b.png)
What is the unit for this type?
I will add these at a later date because it's a minor issue and we don't have much time left this year.

_Originally posted by @Derstilon in https://github.com/yaptide/ui/issues/317#issuecomment-991107796_

**Comment by grzanka** [comment]
Seems fixed now
