### ISSUE TITLE
Fix incorrect image links in editor toolbar

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#42]
![image](https://user-images.githubusercontent.com/26445545/132373223-b2c6e569-1c51-43ee-a8f3-25dad0f746fc.png)
Problem occurs only on localhost

**Comment by Derstilon** [comment]
@grzanka localhost works now but Can you change image paths for github pages?

**Comment by grzanka** [comment]
What do you mean by `change image paths for github pages?` ?

**Comment by grzanka** [comment]
Still present in https://yaptide.github.io/web_dev/

**Comment by grzanka** [comment]
Not relevant anymore
