### ISSUE TITLE
improve cross section view

### ISSUE THREAD

**Issue by ostatni5** [yaptide/ui#58]
- [x] Add label to PlanePoz? mentioning unit [cm]
- [x] Default radius to 1cm
- [x] make blue border lines between each view thinner
- [x] remove info about "objects vertices" #100
- [x] remove ortographic/perspective switch from X,Y,Z cross-sections
- [x] remove possibility to interact with X,Y,Z manipulator (gizmo)
- [x] PlanPoz? range should extend to -100, 100 (let us assume default unit is cm)
- [x] check if "Helper Visible" functionality works
- [x] Minor grid 1cm, Major Grid 10cm
- [x] enable snap mode (snap to the grid)
- [x] right bottom gizmo, Y should point from left to the right, Z from down to up (why Y axis is always parallel to the right border of the screen?)
- [x] left bottom gizmo, Z should point from left to the right, X from down to up (why Y-axis is always parallel to the right border of the screen?)

One moved to new issue:
 #115

**Comment by grzanka** [comment]
@grzanka please provide a wishlist

**Comment by grzanka** [comment]
- [ ] make blue border lines between each view thinner
- [ ] remove info about "objects vertices"
- [ ] remove ortographic/perspective switch from X,Y,Z cross-sections
- [ ] remove possibility to interact with X,Y,Z manipulator (gizmo)
- [ ] PlanPoz? range should extend to -100, 100 (let us assume default unit is cm)
- [ ] Add label to PlanePoz? mentioning unit [cm]
- [ ] check if "Helper Visible" functionality works
- [ ] Minor grid 1cm, Major Grid 10cm
- [ ] Default radius to 1cm
- [ ] enable snap mode (snap to the grid)
- [ ] right bottom gizmo, Y should point from left to the right, Z from down to up (why Y axis is always parallel to the right border of the screen?)
- [ ] left bottom gizmo, Z should point from left to the right, X from down to up (why Y-axis is always parallel to the right border of the screen?)
- [ ] menubar, about should contain info about: deploy date and commit SHA
