### ISSUE TITLE
Files conversion crashes on gh pages instance

### ISSUE THREAD

**Issue by p1003** [yaptide/ui#600]
Tested on https://yaptide.github.io/web_dev/

![image](https://user-images.githubusercontent.com/56313631/188110132-3330e987-88c6-40d6-b2be-e929114645f8.png)

in my case, the UI is stuck forever in Initialising phase (probably loading pyodide).

![Screenshot 2022-09-02 at 12 20 18](https://user-images.githubusercontent.com/7374733/188119077-817b6442-c781-4cd9-afa4-b0bebb01b315.png)

**Comment by grzanka** [comment]
There are only few warnings on deploy phase https://github.com/yaptide/ui/runs/8137390809?check_suite_focus=true#step:6:88

**Comment by grzanka** [comment]
Fixed by https://github.com/yaptide/ui/pull/601
