### ISSUE TITLE
Energy spread not propagate to the beam.dat

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#615]
Whatever we put into beam spread:
![image](https://user-images.githubusercontent.com/7374733/189989403-607a7956-830d-4218-9eaa-3c48873918a1.png)

doesn't propagate into `beam.dat` where we see fixed 1.5
![image](https://user-images.githubusercontent.com/7374733/189989461-e13f7dd4-be32-4b3e-b4fa-202ff1aad69b.png)

**Comment by grzanka** [comment]
It seems a hardcoded value in the converter, see
https://github.com/yaptide/converter/blob/master/converter/shieldhit/beam.py

```
    beam_template: str = """
RNDSEED      	89736501     ! Random seed
JPART0       	2            ! Incident particle type
TMAX0      	{energy:3.1f}  1.5       ! Incident energy; (MeV/nucl)
NSTAT       {nstat:d}    0       ! NSTAT, Step of saving
STRAGG          2            ! Straggling: 0-Off 1-Gauss, 2-Vavilov
MSCAT           2            ! Mult. scatt 0-Off 1-Gauss, 2-Moliere
NUCRE           1            ! Nucl.Reac. switcher: 1-ON, 0-OFF
BEAMPOS {pos_x} {pos_y} {pos_z} ! Position of the beam
BEAMDIR {theta} {phi} ! Direction of the beam
"""
```

**Comment by ostatni5** [comment]
Fixed by https://github.com/yaptide/converter/issues/15

**Comment by grzanka** [comment]
Will be fixed once converter version is bumped on backend and frontend

**Comment by grzanka** [comment]
Fixed by https://github.com/yaptide/ui/pull/717
