### ISSUE TITLE
Migrate sidebar to react

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#636]
![image](https://user-images.githubusercontent.com/26445545/191249720-f6dfbdf2-18c4-4397-b5e6-1635ecdf3279.png)

- [ ] Redesign current layout in react
- [ ] Context change (cards scene scoring) move to speed-dial in an app bar
- [ ] Outliner rewrite using tree view from [MUI components](https://mui.com/material-ui/react-tree-view/) or [custom component from github](https://github.com/minop1205/react-dnd-treeview) preserving hide feature and keeping posibility of drag and drop in a feature.
- [ ] https://github.com/yaptide/ui/issues/639 Object settings grouped in categories proposed by @grzanka
- [ ] Settings tabs in vertical design similar to Blender UI
- [ ] renaming https://github.com/yaptide/ui/issues/643

For more guidelines ask @grzanka

**Comment by grzanka** [comment]
@ostatni5 where would like to have my feedback (as for grouping of objects) ? Here or in separate issue ?

**Comment by ostatni5** [comment]
> @ostatni5 where would like to have my feedback (as for grouping of objects) ? Here or in separate issue ?

New issue
