### ISSUE TITLE
beam source defined from file (`sobp.dat`) in SH12A

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#693]
Beam source should be implemented as one of two mutually exclusive options.
1. As it is now (by setting particle type, energy and other parameters)
2. Using `sobp.dat` file uploaded by the user. This file could be accompanied by couple of additional parameters (like source position) which are defined in SH12A manual.

`sobp.dat` has text format and usually is pretty small (<1MB).

An example of such file: [sobp.txt](https://github.com/yaptide/ui/files/9932518/sobp.txt)

**Comment by ostatni5** [comment]
@grzanka Manual states: 
```
If a file name is specified, e.g. sobp.dat, a projectile will be sampled from the file. Beam settings
specified in the input file beam.dat such as BEAMSIGMA and TMAX0 will be overridden
```
So which exactly fields do we want to stay when using a file?

**Comment by grzanka** [comment]
I would keep only beam position

czw., 10 lis 2022, 11:14 użytkownik Szymon Kania ***@***.***>
napisał:

**Comment by grzanka** [comment]
Beam direction should also stay.
Particle type should stay.

czw., 10 lis 2022, 13:10 użytkownik Leszek Grzanka ***@***.***>
napisał:
