### ISSUE TITLE
Change tabs to spaces to fix wierdly long indents on github

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#697]
This is how github shows our files
![image](https://user-images.githubusercontent.com/26445545/200076287-5af722b8-3be6-49e2-a6ce-5a3f6fd2596f.png)

This is how vscode displays it
![image](https://user-images.githubusercontent.com/26445545/200076315-38d0b87f-c1fe-4b84-824f-d72b1e89cce1.png)

If we change all tabs to spaces it will be more in line with the vscode version and much more readable.

**Comment by ostatni5** [comment]
@Derstilon https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference
