### ISSUE TITLE
missing settings for beam source

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#700]
After creating new project using New button I don't see an option to configure beam source:
![image](https://user-images.githubusercontent.com/7374733/200116130-68f60cd9-899e-490b-b0c1-3c5550b557f5.png)

In the old sidebar it's nicely seen.

![image](https://user-images.githubusercontent.com/7374733/200116100-ea5ca8f9-6531-4909-a8f4-48c1592364ff.png)

**Comment by grzanka** [comment]
Funny that the beam configuration option in new panel activates when I select beam object in old panel:
![image](https://user-images.githubusercontent.com/7374733/200116180-7ef17c52-65f8-4500-a046-c4717f34e2ab.png)

**Comment by ostatni5** [comment]
@grzanka it seems like it is not a problem anymore 
![image](https://user-images.githubusercontent.com/26521377/217818717-19c4d85a-5b82-4710-8e7b-452e54036b03.png)

**Comment by grzanka** [comment]
@ostatni5 you are correct
