### ISSUE TITLE
pyodide broken on C3 deploy

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#714]
![Screenshot 2022-11-09 at 17 53 36](https://user-images.githubusercontent.com/7374733/200892107-4112e52f-cd46-4dd6-8269-577cbc9336bb.png)

**Comment by ostatni5** [comment]
@grzanka  How do we deploy code to C3 if it is removed from GA? https://github.com/yaptide/ui/commit/da51d14d70afb855264cd74220b539ab1fb4c967

**Comment by ostatni5** [comment]
Ah, it is handled by ansible? So it has to be done manually?

**Comment by grzanka** [comment]
Yes, it is handled by ansible

czw., 10 lis 2022, 12:33 użytkownik Szymon Kania ***@***.***>
napisał:
