### ISSUE TITLE
Fix direction of 4 camera'a

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#84]
Cameras should look at the scene from the direction of the clipping plane.
Incorrect (current):
![image](https://user-images.githubusercontent.com/26445545/133831715-f12412e0-c065-45ea-8295-6b348c87a6e7.png)
Sugested (new):
![image](https://user-images.githubusercontent.com/26445545/133831861-5c6f7120-9dfd-4812-994a-45366b66638f.png)
Zone used for testing:
![image](https://user-images.githubusercontent.com/26445545/133831956-4935602a-62fc-40f8-a61f-845d3706b41f.png)
![image](https://user-images.githubusercontent.com/26445545/133831978-b9c32705-1326-4490-a211-788bdfeaa39f.png)

**Comment by grzanka** [comment]
how does clipping plane works ? For example if we have clipping plane define as `y = 6`, then does it remove half-space defined as `y > 6` or `y < 6` ? 
This should be included in the comments in our source code. I've assumed blindly it removes `y < 6`.

**Comment by Derstilon** [comment]
> how does clipping plane works ? For example, if we have clipping plane define as `y = 6`, then does it remove half-space defined as `y > 6` or `y < 6` ?
> This should be included in the comments in our source code. I've assumed blindly it removes `y < 6`.

[Cliping planes](https://threejs.org/docs/#api/en/materials/Material.clippingPlanes) are taken straight from the ThreeJS library. Quoting their API:
>Points in space whose signed distance to the plane is negative are clipped (not rendered).

**Comment by grzanka** [comment]
@Derstilon can't we simply rotate the clipping planes by 180*, such that the normal vectors would point into negative coordinates of their axis ?
Currently half-space with positive coordinates is being shown to the user which is counter-intuitive.

**Comment by Derstilon** [comment]
> @Derstilon can't we simply rotate the clipping planes by 180*, such that the normal vectors would point into negative coordinates of their axis ?
> Currently half-space with positive coordinates is being shown to the user which is counter-intuitive.

I was able to fix this issue by moving cameras from positive parts of the axis to negative.
https://github.com/yaptide/ui/tree/feature/cliping-plane-camera-direction

**Comment by grzanka** [comment]
I saw the fix, but this introduces counter-intuitive view for user, as i.e. with XY clipping plane, user is observing half-space defined as Z>0, while the user would expect to see by default Z<0.
