### ISSUE TITLE
Scoring Qeff

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#864]
We need to update list of scorer quantities: Qeff is missing

![image](https://user-images.githubusercontent.com/7374733/226135351-e2200064-e521-4a46-9a8a-0aea446c25f5.png)

**Comment by grzanka** [comment]
Ignore Aliases

**Comment by kacper1409** [comment]
@grzanka I think I might not have permission to push to ui project.

Im getting: `remote: Permission to yaptide/ui.git denied to kacper1409.`

**Comment by grzanka** [comment]
> @grzanka I think I might not have permission to push to ui project.
> 
> Im getting: `remote: Permission to yaptide/ui.git denied to kacper1409.`

Please try again, I changed your access rights

**Comment by kacper1409** [comment]
Unfortunately I am getting the same error

**Comment by kacper1409** [comment]
But I managed to commit my changes directly to repository via github web ide.

**Comment by grzanka** [comment]
We should discuss it online via zoom, once your changes are pushed please make a PR, even in Draft mode.
