### ISSUE TITLE
File path delimiter issue on Windows

### ISSUE THREAD

**Issue by lequ0n** [yaptide/ui#878]
![image](https://user-images.githubusercontent.com/100755599/227330651-f2855a6c-a177-4758-92dd-c92e4309c639.png)
![image](https://user-images.githubusercontent.com/100755599/227330775-d8ae4788-80af-4feb-a12c-c71a4d4a076b.png)

**Comment by ostatni5** [comment]
@lequ0n could you provide a description of the problem?

**Comment by lequ0n** [comment]
Launching the project with these steps
![image](https://user-images.githubusercontent.com/100755599/228156242-5b8987dc-abfa-465f-9c05-bd510a8da742.png)
leads to
![image](https://user-images.githubusercontent.com/100755599/228156428-8283a289-aa36-4cac-97ce-f2a9e3afa8f0.png)
The problem disappears when the '/' is replaced with '\\'
The problem occurs on windows10
