### ISSUE TITLE
Check r137 of three.js

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#895]
Check if the newly released (r137) version of three.js is compatible with our UI
https://github.com/mrdoob/three.js/releases/tag/r137

**Comment by Derstilon** [comment]
instead of version update issues, we are now working with Dependabot.

**Comment by grzanka** [comment]
We have a lot of code copy-pasted from threejseditor, inside https://github.com/yaptide/ui/blob/master/src/ThreeEditor/
Should we keep as it is or investigate if the common code needs to be migrated or updated as new version of three.js are published ?

**Comment by Derstilon** [comment]
Our editor files got modified so much that I don't think we could get anything useful from newer three editor versions.

**Comment by grzanka** [comment]
> Our editor files got modified so much that I don't think we could get anything useful from newer three editor versions.

OK, then we close this issue
