### ISSUE TITLE
Local and completed simulations have time elapsed counting down

### ISSUE THREAD

**Issue by Derstilon** [yaptide/ui#900]
![image](https://user-images.githubusercontent.com/26445545/230060934-faf900a3-5103-4f0b-9f5b-44af448faf04.png)
Example:
https://yaptide.github.io/web_dev?https://gist.githubusercontent.com/grzanka/f9314302d127836b2e7b3ec76379633d/raw/62eae84905ae452d84017fa8675985c5bfe432d3/plan1.json

**Comment by grzanka** [comment]
Seems fixed now
