### ISSUE TITLE
Air visibility broken on 2D preview

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#905]
When loading this project air is always visible on 2D views:
https://yaptide.github.io/web_dev?https://gist.githubusercontent.com/grzanka/f9314302d127836b2e7b3ec76379633d/raw/62eae84905ae452d84017fa8675985c5bfe432d3/plan1.json
![image](https://user-images.githubusercontent.com/7374733/230214329-124ce93d-1c77-46a0-a9d3-803d843ff426.png)

**Comment by ostatni5** [comment]
@grzanka can be closed ?

**Comment by grzanka** [comment]
To close it we need to adjust example "Treatment plan" and make AirZone invisible:

Then it looks correct:
![image](https://github.com/yaptide/ui/assets/7374733/a90c3181-45e6-4f0a-8f8e-c2493f3f1a69)


By default AirZone is visible and the simulation geometry looks unreadable:
![image](https://github.com/yaptide/ui/assets/7374733/44f167e2-2b12-4338-beab-05a6efefc762)

Before doing that fix I'd wait till https://github.com/yaptide/ui/pull/994 is merged

**Comment by grzanka** [comment]
Lets see if this can be fixed by loading the project, making air invisible, saving the project as JSON and loading again.
