### ISSUE TITLE
UI is freezing when trying to convert problematic file

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#906]
To reproduce:

1. Open the "Treatment plan SOBP" example
2. Go to "Input files" and run "Generate from editor"

Take a look here https://github.com/yaptide/converter/issues/105 as well

**Comment by hendzeld** [comment]
It hangs when loading the result.

The conversion itself is fast.

![obraz](https://github.com/yaptide/ui/assets/128628266/e19529ad-ef43-4b38-9447-dc46f398d72e)
