### ISSUE TITLE
LoopLimit

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#926]
It seems there is now an issue with resizing (introduced in https://github.com/yaptide/ui/pull/563/files)

![image](https://user-images.githubusercontent.com/7374733/232852401-041ae751-37c9-47c5-9607-e9517266dfa1.png)

**Comment by grzanka** [comment]
@ostatni5 says this black popup appears only in developer version (started with `npm run start`)

**Comment by ostatni5** [comment]
Fixed in #1061
